### ISSUE TITLE
Strange way of treating purs ADT values in FFI

### ISSUE THREAD

**Issue by wclr** [keijokapp/purescript-web-cssom-view#10] opened 2024-01-06 18:54 UTC
https://github.com/purescript-web/purescript-web-cssom-view/blob/master/src/Web/CSSOMView/Element.js#L2

This is definitely not the way it should be done, it cannot depend on such implementation details, moreover it works incorrectly.

**Comment by keijokapp** [comment] 2024-01-07 00:21
Thanks for reporting the broken functionality. I'm closing this as a duplicate of #7. I also created PR #11 which should solve both issues.

**Closed as completed by keijokapp** 2024-01-07 00:21 UTC

**Comment by wclr** [comment] 2024-01-07 06:24
Thanks, hope to see it fixed soon.
